name: Lint
on:
  push:
    branches:
      - main
jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v3.4.0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.1
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
