name: Test1.20

on:
  pull_request:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - fixreturncheck

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
            **/testdata/**

      - uses: actions/setup-go@v4

      - run: ./scripts/test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
          verbose: true

